project:
  type: website
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

website:
  title: "Practical Deep Learning for Coders"
  description: "Learn Deep Learning with fastai and PyTorch, 2022"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/tofighi/course22-web
  repo-actions: [edit, issue, source]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/tofighi/course22-web
  sidebar:
    search: true
    collapse-level: 2
    border: false
    pinned: true

editor:
  render-on-save: true

execute:
  freeze: auto

metadata-files:
  - sidebar.yml
