project:
  type: book
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false

book:
  navbar:
    search: true
    pinned: true
    collapse: true
    back-to-top-navigation: true

  sidebar:
    search: true
    collapse-level: 2
    border: false
    pinned: true

  page-navigation: true
  title: "Title"
  subtitle: "with TinyML"
  abstract: "offers readers an entry point to understand comprehensive machine learning systems by grounding concepts in accessible TinyML applications. As resource-constrained edge computing sees rapid expansion, the ability to construct efficient ML pipelines grows crucial. This book aims to demystify the process of developing complete ML systems suitable for deployment - spanning key phases like data collection, model design, optimization, acceleration, security hardening, and integration. The text touches on the full breadth of concepts relevant to general ML engineering across industries and applications through the lens of TinyML. Readers will learn basic principles around designing ML model architectures, hardware-aware training strategies, performant inference optimization, benchmarking methodologies and more. Additionally, crucial systems considerations in areas like reliability, privacy, responsible AI, and solution validation are also explored in depth. In summary, the book strives to equip newcomers and professionals alike with integrated knowledge covering full stack ML system development, using easily accessible TinyML applications as the vehicle to impart universal concepts required to unlock production ML."

  search: true
  repo-url: https://github.com/tofighi/course22-web
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook]
  reader-mode: true
  cover-image: cover.png
  favicon: favicon.png
  page-footer:
    left: |
      left comment
    right: |
      right comment.

  chapters:
    - text: "---"
    - part: FRONT MATTER
      chapters:
      - index.qmd

citation: true

reference-location: margin
citation-location: margin


format:
  html:
    theme: 
      light:
        - cosmo
        - style.scss
        - style-light.scss
      dark:
        - darkly
        - style.scss
        - style-dark.scss
    mainfont: Nunito
    highlight-style: github
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    callout-appearance: simple
    anchor-sections: true
    smooth-scroll: false
    citations-hover: false
    footnotes-hover: false
    fig-width: 8
    fig-height: 6
    number-depth: 3
    toc: true
    toc-depth: 4	
    include-in-header:
      text: <script async src="https://www.googletagmanager.com/gtag/js?id=G-aaaa"></script>

editor:
  render-on-save: true

execute:
  freeze: auto

metadata-files:
  - sidebar.yml
