project:
  type: website
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false


website:
  title: "Practical Deep Learning for Coders"
  description: "Learn Deep Learning with fastai and PyTorch, 2022"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/tofighi/course22-web
  repo-actions: [edit, issue, source]
  favicon: favicon.png
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/tofighi/course22-web
  sidebar:
    search: true
    collapse-level: 2
    border: false
    pinned: true

  page-footer:
    left: |
      Course
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.


format:
  html:
    theme: 
      light:
        - cosmo
        - style.scss
        - style-light.scss
      dark:
        - darkly
        - style.scss
        - style-dark.scss
    mainfont: Nunito
    highlight-style: github
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    callout-appearance: simple
    anchor-sections: true
    smooth-scroll: false
    citations-hover: false
    footnotes-hover: false
    fig-width: 8
    fig-height: 6
    number-depth: 3
    toc: true
    toc-depth: 4	
    include-in-header:
      text: <script async src="https://www.googletagmanager.com/gtag/js?id=G-aaaa"></script>

editor:
  render-on-save: true

execute:
  freeze: auto

metadata-files:
  - sidebar.yml
