project:
  type: book
  output-dir: _book
  preview:
    browser: true
    navigate: true
  render: 
    - "*.qmd"

title-prefix: "noprefix"

    
book:
  navbar:
    search: true
    pinned: true
    collapse: true
    back-to-top-navigation: true

  sidebar:
    search: true
    collapse-level: 2
    border: false
    pinned: true

website:
  title: "Practical Deep Learning for Coders"
  description: "Learn Deep Learning with fastai and PyTorch, 2022"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/tofighi/course22-web
  repo-actions: [edit, issue, source]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/tofighi/course22-web
  sidebar:
    search: true
    collapse-level: 2
    border: false
    pinned: true

format:
  html:
    theme: 
      light:
        - cosmo
        - style.scss
        - style-light.scss
      dark:
        - darkly
        - style.scss
        - style-dark.scss
    mainfont: Nunito
    highlight-style: github
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    callout-appearance: simple
    anchor-sections: true
    smooth-scroll: false
    citations-hover: false
    footnotes-hover: false
    fig-width: 8
    fig-height: 6
    number-depth: 3
    toc: true
    toc-depth: 4	
    include-in-header:
      text: <script async src="https://www.googletagmanager.com/gtag/js?id=G-aaaa"></script>

editor:
  render-on-save: true

execute:
  freeze: auto

metadata-files:
  - sidebar.yml
